### PR TITLE
Translation of the gems chapter

### PR DESCRIPTION
**Pull request by aceawan**
I just finished translating the gems chapter. I tried to be more careful on the spelling mistakes this time to prevent the eyes of the reviewers from bleeding.
I am gonna start the multi-threading chapter tonight :+1:

### CODE REVIEW

**Comment by aceawan** [comment]
Uh ! What are exactly those limits contenprovider.d is complaining about ?

**Comment by wilzbach** [comment]
Maximal length of the source code examples is 48  chars to guarantee a great experience on mobile devices. You can run this locally as well with `--sanitycheck`

**Comment by aceawan** [comment]
Okay, I will do the modifications tonight, thanks !

**Comment by wilzbach** [comment]
> spelling mistake in the name of a file (please work you damn thing)

As said Travis doesn't do more than using `--sanitycheck` - if it works locally it should work here as well. Otherwise please report a bug!
Or in full commands:

```
dub fetch dlang-tour
dub run dlang-tour -- -l . --sanitycheck
```

**Comment by aceawan** [comment]
From now on I will test it locally before pushing commits. Sorry for the bad language, spelling mistakes are frustrating

**Comment by wilzbach** [comment]
> From now on I will test it locally before pushing commits. Sorry for the bad language, spelling mistakes are frustrating

Don't worry. I absolutely understand and I just want to help you to be more productive ;-)

**Comment by wilzbach** [comment]
(and get less annoyed and thus have more fun)

**Comment by aceawan** [comment]
Yay :smile:

**Comment by aceawan** [comment]
> (and get less annoyed and thus have more fun)

I do like having fun, thanks for you help :+1:

**Pull request merged**
