### PR TITLE
Translate welcome-to-d.md

### PR DESCRIPTION
**Pull request by aceawan**
Translate the first page of the D tour to french

### CODE REVIEW

**Comment by wilzbach** [comment]
@aceawan I have sent out an invitation for the French language team, s.t. you can merge PRs (direct write access is disabled as we use Travis to ensure that the examples are runnable).

However, ideally a translation gets reviewed before. Maybe @dlang-tour/french can help?

**Comment by aceawan** [comment]
Maybe @opisano or @llaine could review my translation ?

**Comment by aceawan** [comment]
@wilzbach Did you send an invitation to me ? I didn't receive any notification.

**Comment by wilzbach** [comment]
> @wilzbach Did you send an invitation to me ? I didn't receive any notification.

Jup I did:

image

> Invitations are sent via email and can be accepted at https://github.com/dlang-tour

**Comment by aceawan** [comment]
I have never been added to any group, do you know where I am supposed to get a notification ? 
I have nothing in my notifications menu, my profile says that I am part of no organization and I received no e-mails.

**Comment by wilzbach** [comment]
> I have nothing in my notifications menu, my profile says that I am part of no organization and I received no e-mails.

Hmm, what email address do you use for normal GH notifications? Do they arrive? Anyways, you should be able to see the invitation when you go to https://github.com/dlang-tour

See the [screenshot from a similar question](https://stackoverflow.com/questions/34020327/cant-find-github-invitation-to-join-repo/34024522).

Alternatively try this link: https://github.com/orgs/dlang-tour/invitation

**Comment by aceawan** [comment]
@wilzbach Thank you for you help, I am now a member of the group, yay !

So, if no french speaking member of the D community is available to review my translation, I would ask someone I know who speaks french (but doesn't know anything about D unfortunately) to check my translation for spelling and syntax mistakes, and then I would merge it.

Would that be ok with you ?

**Comment by wilzbach** [comment]
> @wilzbach Thank you for you help, I am now a member of the group, yay !

:tada: 

> So, if no french speaking member of the D community is available to review my translation, I would ask someone I know who speaks french (but doesn't know anything about D unfortunately) to check my translation for spelling and syntax mistakes, and then I would merge it.
> Would that be ok with you ?

Absolutely! If another french-speaking member of the D community steps ahead, they can improve upon the existing translation, which is a lot easier ;-)

**Pull request merged**
